blog/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('blog.views',
    url(r'^$', 'index', name='index'),
    url(r'^(\d+)$', 'show', name='show'),
    url(r'^new$', 'new', name='new'),
    url(r'^category/(\d+)/new$', 'new', name='new'),
    url(r'^(\d+)/edit$', 'edit', name='edit'),
    url(r'^category/(\d+)$', 'show_category', name='show_category'),
    url(r'^(\d+)/like$', 'like', name='like'),
)

stock/urls.py
from django.conf.urls import patterns, include, url

from django.views.generic.base import RedirectView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url='/blog', permanent=False)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^about$', 'stock.views.about', name='about'),
    url(r'^contact$', 'stock.views.contact', name='contact'),
    url(r'^sign_in$', 'stock.views.sign_in', name='sign_in'),
    url(r'^sign_up$', 'stock.views.sign_up', name='sign_up'),
    url(r'^sign_out$', 'django.contrib.auth.views.logout', { 'next_page': '/' }, name='sign_out'),
    url(r'^profile$', 'stock.views.profile', name='profile'),
    url(r'^profile/(\d+)$', 'stock.views.user_profile', name='user_profile'),
)

blog/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime
from django.contrib.auth.models import User
from sanitizer.models import SanitizedCharField, SanitizedTextField

class Category(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'categories'

class Article(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=240)
    content = SanitizedTextField(allowed_tags=['h3', 'h4', 'p', 'a', 'img', 'b', 'i', 'span', 'br', 'ul', 'ol', 'li', 'pre', 'blockquote', 'hr'],
                                 allowed_attributes=['href', 'src', 'style'],
                                 allowed_styles=['font-style', 'font-weight', 'text-decoration', 'vertical-align', 'text-align', 'color', 'background-color', 'float', 'margin', 'padding'],
                                 strip=False)
    publication_date = models.DateTimeField()
    author = models.ForeignKey(User, default=1)
    verified = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.publication_date:
            self.publication_date = timezone.now()
        return super(Article, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-publication_date']

class Like(models.Model):
    user = models.ForeignKey(User)
    article = models.ForeignKey(Article)

blog/forms.py
from django import forms
from blog.models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['category', 'title', 'content']

        widgets = {
            'content': forms.Textarea(attrs={ 'class': 'summernote' })
        }

blog/views.py
from stock.imports import *

_render = render

def render(request, template, context):
    context['categories'] = Category.objects.select_related().all()
    context['recent_articles'] = Article.objects.select_related().filter(verified=True)[:5]
    context['most_popular'] = Article.objects.filter(verified=True).annotate(likes_count=Count('like')).order_by('-likes_count')[:5]
    context['location'] = 'blog'
    return _render(request, template, context)

@require_GET
def index(request):
    articles = paginated(Article.objects.select_related().filter(verified=True), request)
    return render(request, 'blog/index.html', { 'articles': articles })

@require_GET
def show(request, id):
    article = get_object_or_404(Article, pk=id)
    likes = article.like_set.all()
    if request.user.is_authenticated():
        is_liked = likes.filter(user=request.user).exists()
    else:
        is_liked = False
    return render(request, 'blog/show.html', { 'article': article, 'likes': likes, 'is_liked': is_liked })

@login_required
def new(request, category = None):
    if request.method == 'POST':
        form = ArticleForm(request.POST)

        if form.is_valid():
            article = form.save()
            article.author = request.user
            article.save()
            messages.info(request, 'The article is created.')
            return redirect('blog:show', article.id)
    else:
        form = ArticleForm(initial={ 'category': category })

    return render(request, 'blog/new.html', { 'form': form })

@login_required
def edit(request, id):
    article = get_object_or_404(Article, pk=id)

    if article.author != request.user:
        return redirect('blog:index')

    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)

        if form.is_valid():
            form.save()
            messages.info(request, 'The article is updated.')
            return redirect('blog:show', article.id)
    else:
        form = ArticleForm(instance=article)

    return render(request, 'blog/edit.html', { 'form': form })

@require_POST
@login_required
def like(request, id):
    article = get_object_or_404(Article, pk=id)

    likes = article.like_set.all()
    like = article.like_set.filter(user=request.user)

    if like.exists():
        like.delete()
        active = False
    else:
        article.like_set.create(user=request.user)
        active = True

    return HttpResponse(json.dumps({ 'active': active, 'likes_count': likes.count() }), content_type='application/json')

@require_GET
def show_category(request, id):
    category = get_object_or_404(Category, pk=id)
    articles = paginated(category.article_set.filter(verified=True), request)
    return render(request, 'blog/show_category.html', { 'category': category, 'articles': articles })

blog/templates/blog/_articles.html
{% include 'blog/_paginator.html' with collection=articles %}

<section class="articles">
  {% for article in articles %}
    <article>
      <time>
        <span class="glyphicon glyphicon-time"></span>
        {{ article.publication_date|date:'Y-m-d H:m' }}
      </time>
      <div class="category">
        <span class="glyphicon glyphicon-folder-open"></span>
        &nbsp;
        {% link_to article.category.title 'blog:show_category' article.category.id %}
      </div>
      <h3>{% link_to article.title 'blog:show' article.id %}</h3>
      <div class="content">
        {{ article.content|truncatewords_html:200|safe }}

        <a href="{% url 'blog:show' article.id %}" class="green-btn green-btn-wi read-more">
          <span class="glyphicon glyphicon-arrow-right"></span>
          Read more
        </a>
      </div>
      <div class="author">
        <b>Author:</b>
        {% link_to article.author.username 'user_profile' article.author.id %}
      </div>
      <div class="like">
        <button>
          <span class="glyphicon glyphicon-star"></span>
        </button>
        <span class="count">{{ article.like_set.count }}</span>
      </div>
    </article>
  {% endfor %}
</section>

{% include 'blog/_paginator.html' with collection=articles %}

blog/templates/blog/_paginator.html
{% if collection.paginator.num_pages > 1 %}
<ul class="pagination">
  {% if collection.number != 1 %}
    <li><a href="?"><span class="glyphicon glyphicon-step-backward"></span></a></li>
  {% else %}
    <li class="disabled"><a href="#"><span class="glyphicon glyphicon-step-backward"></span></a></li>
  {% endif%}

  {% if collection.has_previous %}
    <li><a href="?page={{ collection.previous_page_number }}"><span class="glyphicon glyphicon-chevron-left"></span></a></li>
  {% else %}
    <li class="disabled"><a href="#"><span class="glyphicon glyphicon-chevron-left"></span></a></li>
  {% endif%}

  <li class="active" ><a href="#">{{ collection.number }}</a></li>

  {% if collection.has_next %}
    <li><a href="?page={{ collection.next_page_number }}"><span class="glyphicon glyphicon-chevron-right"></span></a></li>
  {% else %}
    <li class="disabled"><a href="#"><span class="glyphicon glyphicon-chevron-right"></span></a></li>
  {% endif%}

  {% if collection.number != collection.paginator.num_pages %}
    <li><a href="?page={{collection.paginator.num_pages}}"><span class="glyphicon glyphicon-step-forward"></span></a></li>
  {% else %}
    <li class="disabled"><a href="#"><span class="glyphicon glyphicon-step-forward"></span></a></li>
  {% endif%}
</ul>
{% endif %}

blog/templates/blog/base.html
{% extends 'base.html' %}

{% load cache %}

{% block content %}
  <div class="row">
    <section class="col-md-9">
      {% block blog_content%}{% endblock %}
    </section>
    {% cache 20 blockaside %}
    <aside class="sidebar col-md-3">
      <section class="recent_articles_block">
        <h3>Recent articles:</h3>

        {% for article in recent_articles %}
          <article>
            <time>
              <span class="glyphicon glyphicon-time"></span>
              {{ article.publication_date|date:'Y-m-d H:m' }}
            </time>
            <div class="category">
              <span class="glyphicon glyphicon-folder-open"></span>
              &nbsp;
              {% link_to article.category.title 'blog:show_category' article.category.id %}
            </div>
            {% link_to article.title 'blog:show' article.id 'attrs:class ="link"' %}
          </article>
        {% endfor %}
      </section>
      <section class="most_popular_block">
        <h3>Most popular:</h3>

        {% for article in most_popular %}
          <article>
            <time>
              <span class="glyphicon glyphicon-time"></span>
              {{ article.publication_date|date:'Y-m-d H:m' }}
            </time>
            <div class="category">
              <span class="glyphicon glyphicon-folder-open"></span>
              &nbsp;
              {% link_to article.category.title 'blog:show_category' article.category.id %}
            </div>
            {% link_to article.title 'blog:show' article.id 'attrs:class ="link"' %}
          </article>
        {% endfor %}
      </section>
      <section class="categories_block">
        <h3>Categories:</h3>

        {% for category in categories %}
          <article>
            {% link_to category.title 'blog:show_category' category.id %}&nbsp;
            {{ category.article_set.count }}
          </article>
        {% endfor %}
      </section>
    </aside>
    {% endcache %}
  </div>
{% endblock %}

blog/templates/blog/edit.html
{% extends 'base.html' %}

{% block title %}Edit article{% endblock %}

{% block content %}
  <h2>Edit Article</h2>

  <form action="{% url 'blog:edit' form.instance.id %}" method="post">{% csrf_token %}
    {% include '_form.html' %}

    <button type="submit" class="btn btn-default">Update</button>
  </form>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %}Blog{% endblock %}

{% block blog_content %}
  {% if user.is_authenticated %}
    <a href="{% url 'blog:new' %}" class="green-btn green-btn-wi">
      <span class="glyphicon glyphicon-plus"></span>
      New article
    </a>
    <div class="clear"></div>
  {% endif %}
  {% include 'blog/_articles.html' %}
{% endblock %}

blog/templates/blog/new.html
{% extends 'base.html' %}

{% block title %}New article{% endblock %}

{% block content %}
  <h2>New Article</h2>

  <form action="{% url 'blog:new' %}" method="post">{% csrf_token %}
    {% include '_form.html' %}

    <button type="submit" class="btn btn-default">Create</button>
  </form>
{% endblock %}

blog/templates/blog/paginator.html
{% if collection.paginator.num_pages > 1 %}
<ul class="pagination">
  {% if collection.number != 1 %}
    <li><a href="?"><span class="glyphicon glyphicon-step-backward"></span></a></li>
  {% else %}
    <li class="disabled"><a href="#"><span class="glyphicon glyphicon-step-backward"></span></a></li>
  {% endif%}

  {% if collection.has_previous %}
    <li><a href="?page={{ collection.previous_page_number }}"><span class="glyphicon glyphicon-chevron-left"></span></a></li>
  {% else %}
    <li class="disabled"><a href="#"><span class="glyphicon glyphicon-chevron-left"></span></a></li>
  {% endif%}

  <li class="active" ><a href="#">{{ collection.number }}</a></li>

  {% if collection.has_next %}
    <li><a href="?page={{ collection.next_page_number }}"><span class="glyphicon glyphicon-chevron-right"></span></a></li>
  {% else %}
    <li class="disabled"><a href="#"><span class="glyphicon glyphicon-chevron-right"></span></a></li>
  {% endif%}

  {% if collection.number != collection.paginator.num_pages %}
    <li><a href="?page={{collection.paginator.num_pages}}"><span class="glyphicon glyphicon-step-forward"></span></a></li>
  {% else %}
    <li class="disabled"><a href="#"><span class="glyphicon glyphicon-step-forward"></span></a></li>
  {% endif%}
</ul>
{% endif %}

blog/templates/blog/show.html
{% extends 'blog/base.html' %}

{% block title %}{{ article.title }}{% endblock %}

{% block blog_content %}
  <article class="article">
    <time>
      <span class="glyphicon glyphicon-time"></span>
      {{ article.publication_date|date:'Y-m-d H:m' }}
    </time>
    <div class="category">
      <span class="glyphicon glyphicon-folder-open"></span>
      &nbsp;
      {% link_to article.category.title 'blog:show_category' article.category.id %}
    </div>
    <h1>{{ article.title }}</h1>
    <div class="content">{{ article.content|safe }}</div>
    <div class="author">
      <b>Author:</b>
      {% link_to article.author.username 'user_profile' article.author.id %}
    </div>
    <div class="like {% if user.is_authenticated %}active{% endif %}" data-url="{% url 'blog:like' article.id %}">
      {% csrf_token %}
      <button class="{% if is_liked %}active{% endif %}">
        <span class="glyphicon glyphicon-star"></span>
      </button>
      <span class="count">{{ likes.count }}</span>
    </div>
  </article>

  {% if article.author == user %}
    <a href="{% url 'blog:edit' article.id %}" class="green-btn green-btn-wi">
      <span class="glyphicon glyphicon-pencil"></span>
      Edit article
    </a>
  {% endif %}
{% endblock %}

blog/templates/blog/show_category.html
{% extends 'blog/base.html' %}

{% block title %}{{ category.title }}{% endblock %}

{% block blog_content %}
  <article class="category">
    <h1>{{ category.title }}</h1>
    {% if user.is_authenticated %}
      <a href="{% url 'blog:new' category.id %}" class="green-btn green-btn-wi">
        <span class="glyphicon glyphicon-plus"></span>
        New article
      </a>
      <div class="clear"></div>
    {% endif %}
    {% include 'blog/_articles.html' %}
  </article>
{% endblock %}